const express = require("express");
const router = express.Router();
const protect = require("../middleware/auth");
const upload = require("../middleware/upload");
const {createBlog,getAllBlogs,getBlogById,updateBlog,deleteBlog} = require("../controllers/blogController");
router.post("/", protect,upload.array("images", 5), createBlog);
router.get("/", getAllBlogs);
router.get("/:id",getBlogById);
router.put("/:id",protect,updateBlog);
router.delete("/:id",protect,deleteBlog);
module.exports = router;